---
format:
  html:
    header-includes: |
        <link rel="icon" type="image/png" sizes="32x32" href="../_extensions/InseeFrLab/onyxia/favicon-32x32.png">
---

# Acquisition

## Images satellite

### Pléiades

Les images Pléiades présentent l’avantage d’offrir une très haute résolution (50 cm). Toutefois, elles sont la propriété d’Airbus, ce qui limite leur accessibilité : l’acquisition passe généralement par un achat de licence. En tant qu’institution française, nous bénéficions d'un accès gratuit à ces données via [Dinamis](https://dinamis.data-terra.org/). Il suffit de créer un compte sur Dinamis et de réaliser une demande d’accès.
Nous avons un contact à l'IGN pour simplifier la procédure et il nous transmet les images directement. Toutefois, même avec ce canal, il reste nécessaire de créer un compte Dinamis et de signer un contrat de licence d'utilisation.

Lorsque les images sont disponibles, notre interlocuteur à l’IGN nous en informe par mail, en nous transmettant les accès à un serveur FTP. Les données peuvent alors être extraites puis transférées sur le S3 du namespace `projet-slums-detection` au sein du Datalab, selon la structure décrite dans @data-raw.  

::: {.callout-tip}
# Comment récupérer les images Pléiades de l'IGN ?

1. Ouvrir un service VSCode sur le Datalab. ⚠️ Pour les volumes importants, pensez à augmenter la persistance (ex : 500Gi) lors du lancement du service.
2. Cloner le [dépot d'inférence](https://github.com/InseeFrLab/satellite-images-inference) etaccéder au script `bash/download_pleiades_ign.sh`.
3. Renseigner les informations spécifiques au serveur FTP ainsi que les arguments nécessaires (département, année).
4. Exécuter le script pour télécharger les données localement dans le service. Vous pouvez ensuite explorer les fichiers comme d'habitude (`cd`, `ls`, etc.). 
5. Une fois en local, vérifiez que les images soient bien au format `.tif`, si ce n'est pas le cas, exécuter le script `src/write_jp2_to_tiff.py` pour les convertir et les stocker sur le S3
:::


### Sentinel-2

Pour un accès libre et beaucoup plus rapide, l’utilisation des images Sentinel-2 constitue une alternative intéressante. Ces images ont une résolution de 10 mètres.
Les images Sentinel-2 peuvent être récupérées via différentes plateformes comme Google Earth Engine, Sentinel Hub ou encore Copernicus Data Space Ecosystem.
Un exemple d'utilisation et de téléchargement de ces données est disponible dans le dépôt [Hackathon NTTS 2025](https://github.com/InseeFrLab/hackathon-ntts-2025), en consultant le script `preprocess/main_nuts.py`.


## Labels (pour l'entraînement du modèle)

### BDTOPO

La BD TOPO est une description vectorielle 3D (structurée en objets) des éléments du territoire et de ses infrastructures, de précision métrique, exploitable à des échelles allant du 1 : 2 000 au 1 : 50 000.

Les objets de la BD TOPO® sont regroupés par thèmes :

- Administratif (limites et unités administratives) ;
- **Bâti (constructions)** ;
- Hydrographie (éléments ayant trait à l’eau) ;
- Lieux nommés (lieu ou lieu-dit possédant un toponyme et décrivant un espace naturel ou un lieu habité) ;
- Occupation du sol (végétation, estran, haie) ;
- Services et activités (services publics, stockage et transport des sources d'énergie, lieux et sites industriels) ;
- Transport (infrastructures du réseau routier, ferré et aérien, itinéraires) ;
- Zones réglementées (la plupart des zonages faisant l'objet de réglementations spécifiques).

Dans notre cas, seule la couche **Bâti** a été utilisée.

::: {.callout-tip}
# Comment récupérer les données de la BDTOPO

Les données de la BDTOPO sont accessibles au format archivé 7z soit en shapefile soit en geopackage à l'adresse suivante : [https://geoservices.ign.fr/bdtopo#telechargementgpkgreg]().
Elle est stockée par département.

:::



### COSIA

Les cartes CoSIA décrivent la couverture du sol, soit la nature du sol, selon 16 classes (bâtiment, surface d’eau, conifère, culture, broussaille...). Cette description du sol est produite pour tout le territoire français (métropole et DROM) et avec une haute résolution de 20 cm par pixel. Ces annotations ont été obtenues par l'IGN à l'aide d'un modèle de ML. Il faut donc bien garder en tête qu'**on utilise des prédictions d'un modèle comme ground truth**. 

::: {.callout-tip}
# Comment récupérer les données de COSIA

1. Accéder au site [COSIA](https://cosia.ign.fr/info#export)
2. Remplir le formulaire d'accès et sélectionner le territoire d'intérêt. Télécharger le fichier `.zip`
3. L'importer dans un service du Datalab, le décompresser (commande `unzip` sous Linux) et organiser les fichiers selon la structure attendue sur S3.

:::
