# 🌍 Geoserver

Une fois les prédictions faites, il est important de les intégrer au [Geoserver](https://geoserver-satellite-images.lab.sspcloud.fr/geoserver) *(demander les identifiants à l'équipe)*.

---

## 📥 Étape 1 : Envoi vers le pvc du GeoServer via ArgoWorkflow

Un remplissage dans le pvc du GeoServer se fait directement lors de l’[inférence via le template ArgoWorkflow](https://github.com/InseeFrLab/satellite-images-inference/blob/9c9ef808fdce7ecea29a568e04c41354258c3c61/argo-workflows/predict-workflows.yaml#L86).  
Cette étape consiste à stocker les images Pléiades **et** les prédictions dans le GeoServer.

---

## 🗂️ Étape 2 : Création manuelle des entrepôts et couches dans le GeoServer

Il est important de créer un entrepôt et une couche pour utiliser les données sous forme de flux WMS dans la webapp.
Pour l’instant, **cette étape est manuelle** : nous n’avons pas trouvé de méthode automatique.

---

## 📷 Pour les *Images*

1. **Entrepôt**  
   - Menu **Données > Entrepôts** (à gauche)  
   - Cliquez sur **+ Ajouter un nouvel entrepôt**  
   - Choisir **ImageMosaic**  
   - `name = <DEP>_<YEAR>`  
   - Parcourir le dossier `PLEIADES/<DEP>/<YEAR>`  
   - ➡️ *Sauvegarder*

2. **Couche**  
   - Menu **Données > Couches**  
   - Cliquez sur **+ Ajouter une nouvelle couche**  
   - Sélectionner l’entrepôt créé  
   - `name = <DEP>_<YEAR>`, `title = <YEAR>`  
   - ➡️ *Sauvegarder*

---

## 🧠 Pour les *Prédictions*

1. **Entrepôt**  
   - Menu **Données > Entrepôts**  
   - Cliquez sur **+ Ajouter un nouvel entrepôt**  
   - Choisir **Geopackage**  
   - `name = <DEP>_PREDICTIONS_<YEAR>`  
   - Parcourir le fichier :  
     `PREDICTIONS/PLEIADES/<DEP>/<YEAR>/Segmentation-multiclasse/1/predictions.gpkg`  
   - ➡️ *Sauvegarder*

2. **Couche**  
   - Menu **Données > Couches**  
   - Cliquez sur **+ Ajouter une nouvelle couche**  
   - Sélectionner l’entrepôt créé  
   - `name = <DEP>_PREDICTIONS_<YEAR>`, `title = <DEP>_PREDICTIONS_<YEAR>`  
   - Dans l’onglet **Emprises** :  
     - Cliquer sur **Basées sur les données**, puis **Calculer depuis les emprises natives**  
   - Dans **Publication > Style par défaut** : `dirag:style_multiclass`  
   - ➡️ *Sauvegarder*

---

⚠️ **Vérification**  
Pour vérifier que tout s'est bien passé :  
Menu **Prévisualisation de la couche** (à gauche) → Cliquer sur **OpenLayers** de la couche souhaitée pour la prévisualiser.

---

# 🧩 Webapp CRaTT

Une fois les nouvelles couches créées, il faut les intégrer dans la webapp CRaTT :  

1. Cloner le [dépôt Git](https://github.com/InseeFrLab/satellite-images-webapp.git)  
2. Modifier le code pour ajouter le nouveau **couple Département / Année** :  
   - Dans [`components/config.js`](https://github.com/InseeFrLab/satellite-images-webapp/blob/main/src/components/config.js)  
   - Et dans [`utils/config.js`](https://github.com/InseeFrLab/satellite-images-webapp/blob/main/src/utils/config.js)  

💡 Le `git push` déclenche automatiquement un rebuild du site. Les nouvelles couches seront visibles après quelques minutes (une fois que l’action GitHub est terminée).

---
