## Les images satellitaires

-  Une source peu utilisée....
-  .... mais a [**fort potentiel**]{.orange}
    -   données très [**haute résolution**]{.blue2}
    -   couverture [**étendue**]{.blue2}
    
::: notes
Les images satellitaires sont très peu utilisée, et pourtant il s'agit de données très riches qui offrent des bonnes opportunités pour améliorer et créer des indicateurs. En effet, il s'agit de données très haute résolution qui couvre une grande partie du territoire. Ces données sont d'ailleurs très utile dans le cadre du recensement de la population. --> diapo suivante
:::

## Un bon cas d'usage : le recensement dans les DROM

- [**Mauvaise qualité**]{.orange} des [**données administratives**]{.blue2} dans les DROM
    -   [**enquête cartographique**]{.blue2} pour une base de sondage exhaustive

- [**Contrôle qualité**]{.orange} des enquêtes cartographiques
    -   [**données satellitaires**]{.blue2} 

::: notes
Le recensement de la population en france et particulièrement sur les territoires des DROM en font un bon cas d'usage. En effet, dû à la mauvaise qualité des données administrative dans ces territoires une enquête cartographique est réalisée en amont de la collecte pour avoir une base de sondage exhaustive. Afin de réaliser un contrôle qualité de cette enquête cartographique, les données satellites ont été utilisées. Un exemple d'utilisation de l'utilisation des données satellites sur le contrôle qualité des enquête carto à Mayotte sera présenté juste après.
:::

## Nos cas d'usage

-   Identifier les zones avec [**une forte densité de bâti**]{.orange} 🏘️\
-   Détecter les [**évolutions du bâti**]{.blue2} de façon automatique\
-   [**Répondre à une urgence**]{.red2} 🚨 : cyclone "Chido" à Mayotte

::: notes
-   Identifier les zones avec [**une forte densité de bâti**]{.blue2}, c'est à dire [**les zones prioritaires**]{.blue2} pour l'enquête cartographique et pour lesquelles il faut envoyer le plus d'agents.
-   Pouvoir détecter [**les évolutions du bâti**]{.blue2} de façon automatique, notamment depuis le précédent inventaire du bâti effectué\
-   [**Répondre à une urgence**]{.red2} : les conséquences du cyclone "Chido" sur le bâti à Mayotte

-> On va maintenant se pencher sur la méthodologie utilisée pour répondre à ces besoins.
:::