## Cas d'usage : Le recensement à Mayotte

-   Depuis 2021 : recensement avec fonctionnement [**quinquennal**]{.orange}
    -   territoire divisé en îlots
    -   ilôts repartis dans 5 groupes de rotation

<!-- Ajouter graphiques cycle recensement -->

::: notes
Pour précisier, ces travaux font référence aux enquêtes ayant eu lieu de 2021 à 2024. En 2025, du fait du cyclone Chido, la cinquième et dernière enquête du premier cycle n’a pas pu être réalisée. Il a alors été décidé de réaliser de nouveau un recensement exhaustif de la population qui aura lieu du 27 novembre 2025 au 10 janvier 2026.

A la différence des autres départements, à Mayotte la méthode est différente entre les habitations en dur et les habitations de fortune. Pour les habitations de fortune, le recensement y est exhaustif que ça soit en petite ou grande commune, par contre pour les logements en dur; il n'est exhaustif qu'en petite commune et par sondage dans les communes de plus de 10 000 habitants.
:::

## Contrôle de la couverture de l'enquête cartographique

-   Enquête cartographique → alimente le RIL → constitue la [**base de sondage**]{.orange} des logements en dur des communes ≥ 10 000 hab

-   [**Sous-estimation**]{.orange} du nb logements dans l'enquête carto → populations et logements déduit [**sous-estimé**]{.orange}


 →  [**Contrôle qualité**]{.orange} de l'enquête cartographique [**important**]{.blue} : utilisation des [**données satellites**]{.orange}

## Identification des îlots avec une sous-couverture potentielle

# Données utilisées

2 évolutions comparées : 

-   [**surface bâtie**]{.orange} prédites entre 2017 et 2021/2022
    -   [*données satellites*]{.grey}

-   [**nombre de logements**]{.orange} entre le RP 2017 et les enquêtes cartographiques 2021/2022 
    -   [*collecte 2017, enquête cartographique 2021, 2022*]{.grey}

## Identification des îlots avec une sous-couverture potentielle

### Construction d'un score 

<div style="background-color: #f0f0f0; border: 1px solid #ccc; border-radius: 5px; padding: 5px 10px; font-size: 0.8em; text-align: center; width: fit-content; margin: 0 auto;">
  On s'intéresse uniquement aux îlots pour lesquels l'évolution du bâti issue des données satellites est plus importante que l'évolution issue de l'enquête cartographique
</div>


Le $score$ est calculé sur 2 sous ensemble : 
-   ensemble des logements
-   uniquement les logements en dur

### Construction d'un score 

$score=score_{évolution} + score_{sens} + score_{distance}$ 

$score_{évolution}$ vaut :


-   1 si l’évolution du nombre de logements dans le recensement est plus faible que celle de la surface bâtie (données satellites)


-   0 sinon

 $score_{sens}$ vaut :


-   1 si l’évolution du nombre de logements dans le recensement est dans le sens opposé de celle de la surface bâtie (données satellites)


-   0 sinon


$score_{distance}$ vaut :


-   0 si $distance\_{ilot} ≤ Q1$


-   1 si $Q1 < distance\_{ilot} ≤ médiane$


-   2 si $médiane < distance\_{ilot} ≤ Q3$


-   3 si $distance\_{ilot} > Q3$


### Définition des ordres de priorité

| Ordre de priorité | Score (ensemble des logements – logements durs) |
|-------------------|-------------------------------------------------|
| 1                 | 5-5                                             |
| 2                 | 4-5 ou 5-4                                      |
| 3                 | 4-4                                             |
| 4                 | 3-5 ou 5-3                                      |
| 5                 | 3-4 ou 4-3                                      |
| 6                 | 3-3                                             |
| 7                 | 2-5 ou 5-2                                      |
| 8                 | 2-4 ou 4-2                                      |


: Ordres de priorité des îlots avec sous-couverture de logements supposée {#tbl-ordre_p}


-> [**cartographie complémentaire**]{.orange} sur les îlots avec un ordre de priorité 1 à 8 
